version = 0.1
[dev.deploy.parameters]
stack_name = "voxora-api"
resolve_s3 = true
s3_prefix = "voxora-api"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
