AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Text to Speech Lambda Function

Globals:
  Api:
    Cors:
      AllowOrigins:
        - "'*'"
      AllowHeaders:
        - "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods:
        - "'POST, GET, OPTIONS, PUT, DELETE'"
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        BUCKET_NAME: !Ref AudioBucket

Resources:
  TextToSpeechFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: text-to-speech.handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /text-to-speech
            Method: post
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AudioBucket
        - Statement:
            - Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: '*'

  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - '*'
            MaxAge: 3000

Outputs:
  TextToSpeechApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/text-to-speech/"
  AudioBucketName:
    Description: Name of the S3 bucket for audio files
    Value: !Ref AudioBucket
